In [7]:
import numpy as np
import time

In [8]:
#comparision py_list and ndarray


size = 100000
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time {start-end} second")

#testing numpy arrys 
np_arr = np.array(py_list)
start=time.time()
sq_array = np_arr**2
end=time.time()
print(f"numpy array time {start-end} second")

python list time -0.007039785385131836 second
numpy array time -0.0015544891357421875 second


In [9]:
import sys
print(f"memory of pyhton list in bytes = {sys.getsizeof(py_list)*len(py_list)}")
print(f"memory of numpy arrya in bytes = {np_arr.nbytes}")

memory of pyhton list in bytes = 80005600000
memory of numpy arrya in bytes = 800000


In [6]:
#some basic properties like shape,dtype
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr,type(arr),arr.dtype,arr.shape)

arr2=np.array([1,2,3,4,5,"prime"])
print(arr2,type(arr2),arr2.dtype,arr2.shape)

arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d,type(arr2d),arr2d.dtype,arr2d.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> int64 (3, 3)


In [88]:
#creating array using built in methods

arr1=np.zeros((2,3), dtype="int64")
print(arr1, arr1.shape, arr1.dtype)

arr2=np.ones((3,))
print(arr2, arr2.shape, arr2.dtype)

arr3=np.eye(4)
print(arr3, arr3.shape, arr3.dtype)

arr4=np.full((3,4),7)
print(arr4, arr4.shape, arr4.dtype)

arr5=np.arange(0,11,2) #this is exactly line range function
print(arr5, arr5.shape, arr5.dtype)

arr6=np.linspace(1,10,5)
print(arr6, arr6.shape, arr6.dtype)

[[0 0 0]
 [0 0 0]] (2, 3) int64
[1. 1. 1.] (3,) float64
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4) float64
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]] (3, 4) int64
[ 0  2  4  6  8 10] (6,) int64
[ 1.    3.25  5.5   7.75 10.  ] (5,) float64


In [89]:
#properties
arr=np.array([[10,20,30],[40,50,60],[70,80,90]],dtype="U21")
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)

#type casting
float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)

[['10' '20' '30']
 ['40' '50' '60']
 ['70' '80' '90']]
(3, 3)
9
2
[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]] float64


In [116]:
#operation on numpay arrays

arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

arr_reshaped=arr.reshape(3,2)
print(arr_reshaped,arr_reshaped.shape)

arr_flattend=arr.flatten()
print(arr_flattend,arr_flattend.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [90]:
#indexing of numpay arryas 
arr=np.array([1,2,3,4,5])

arr2d=np.array([[10,20,30],[30,50,60]])
print(arr[0])
print(arr[4])

#2D dimentional indexing
print(arr2d[1][1]) #50

#fancy indexing
idx=[0,1,4]
print(arr[idx])

#boolean indexing
print(arr[arr>1]) 
print(arr[arr%2==0])
print(arr[arr%2!=0])

#slicing
print(arr[::2]) #[start:stop:step]


1
5
50
[1 2 5]
[2 3 4 5]
[2 4]
[1 3 5]
[1 3 5]


In [148]:
#copy vs view
arr=[1,2,3,4,5]
sub_arr=arr[1:3]
print(sub_arr)
sub_arr[0]=100
print(sub_arr)
print(arr)


n_arr=np.array([1,2,3,4,5])
sub_array=n_arr[1:3] #if dont want to change in original use .copy()
print(sub_array)
sub_array[0]=200
print(sub_array)
print(n_arr)

[2, 3]
[100, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[  1 200   3   4   5]


In [151]:
#common data type 
arr=np.array([3+3j])
arr1=np.array([6+2j])
print(arr+arr1,arr.shape,arr.dtype)
print(arr-arr1,arr.shape,arr.dtype)

[9.+5.j] (1,) complex128
[-3.+1.j] (1,) complex128


In [16]:
#multidimension array
import numpy as np
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

sum_of_coloums=np.sum(arr2d,axis=0)
print(sum_of_coloums)

sum_of_rows=np.sum(arr2d,axis=1)
print(sum_of_rows)

#slicing in 2D
print(arr2d[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [38]:
#3D array
arr3d=np.array([[[1,2], [3,4], [5,6]], [[7,8], [9,10], [11,12]]])
print(arr3d,arr3d.size,arr3d.shape,arr3d.dtype)

#indexing
print(arr3d[1,1,0])

#slicing in 3D

print(arr3d[:,0,:])#first row of both matrix
print(arr3d[:,:,0])#first coloumn of both the matrix

arr3d[:, 0, :]=100 #we can replace element like this 
print(arr3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] 12 (2, 3, 2) int64
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[100 100]
  [  3   4]
  [  5   6]]

 [[100 100]
  [  9  10]
  [ 11  12]]]


In [47]:
#vectorization
arr=np.array([1,2,3,4,5])
arr1=np.array([6,7,8,9,10])
print(arr[0]+100)
print(arr**2)
print(arr[4]**2)
print(arr+arr1)

#we can say perform lots of action on array with numpy function

101
[ 1  4  9 16 25]
25
[ 7  9 11 13 15]


In [55]:
#broadcasting

arr1=np.array([1,2,3,4,5])
arr2=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(arr1.shape)
print(arr2.shape)
print(arr1+arr2)

(5,)
(2, 5)
[[ 11  22  33  44  55]
 [ 61  72  83  94 105]]


In [64]:
#normalization

arr=np.array([[1,2], [3,4]])
mean=(np.mean(arr))
std_dev=(np.std(arr))

normalization=(arr-mean)/std_dev
print(normalization)

print(mean)
print(std_dev)
print(np.sqrt(5/4)) #varification step

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895
1.118033988749895


In [74]:
# mathematical functions 

#(1) Aggregation

arr=np.array([1,2,3,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr)) #index of min element
print(np.argmax(arr)) #index of max element
print(np.std(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.var(arr))

15
120
1
5
0
4
1.4142135623730951
3.0
3.0
2.0


In [76]:
#power function
arr=np.array([1,2,3,4,5])
print(np.square(arr))
print(np.sqrt(arr))
print(np.power(arr,2))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[ 1  4  9 16 25]


In [79]:
#log & exponential 
arr=np.array([1,2,3,4,5])
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [83]:
#rounding
print(np.round(5.43))
print(np.ceil(5.53))
print(np.floor(5.53))
print(np.trunc(5.53))


5.0
6.0
5.0
5.0


In [86]:
#some other function
arr=np.array([1,2,3,3,4,5,-10])
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr)) #give value without sign


# Apart from these there is lot more function

[-10   1   2   3   4   5]
[-10   1   2   3   3   4   5]
[ 1  2  3  3  4  5 10]
